name: barcoder
description: Simple CLI barcode generator.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

dependencies:
  args: ^2.4.2
  barcode: ^2.2.6
  quiver: ^3.2.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  barcoder: